### ISSUE TITLE
Running the project with docker compose fails due to migration problems

### ISSUE THREAD

**Issue by scarecrow98** [peermetrics/peermetrics#1]
After running `docker compose up` the `peermetrics-api` and `peermetrics-postgres` containers fail because of non-existing user relation.

Here are the docker logs:

> peermetrics-api-1       | Operations to perform:
peermetrics-api-1       |   Apply all migrations: admin, auth, contenttypes, sessions
peermetrics-api-1       | Running migrations:
peermetrics-postgres-1  | 2024-03-27 15:28:16.728 UTC [44] ERROR:  relation "users" does not exist
peermetrics-postgres-1  | 2024-03-27 15:28:16.728 UTC [44] STATEMENT:  ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_users_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED
peermetrics-api-1       | Traceback (most recent call last):
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
peermetrics-api-1       |     return self.cursor.execute(sql, params)
peermetrics-api-1       | psycopg2.errors.UndefinedTable: relation "users" does not exist
peermetrics-api-1       |
peermetrics-api-1       |
peermetrics-api-1       | The above exception was the direct cause of the following exception:
peermetrics-api-1       |
peermetrics-api-1       | Traceback (most recent call last):
peermetrics-api-1       |   File "manage.py", line 15, in <module>
peermetrics-api-1       |     execute_from_command_line(sys.argv)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
peermetrics-api-1       |     utility.execute()
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
peermetrics-api-1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
peermetrics-api-1       |     self.execute(*args, **cmd_options)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
peermetrics-api-1       |     output = self.handle(*args, **options)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
peermetrics-api-1       |     res = handle_func(*args, **kwargs)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 232, in handle
peermetrics-api-1       |     post_migrate_state = executor.migrate(
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 117, in migrate
peermetrics-api-1       |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
peermetrics-api-1       |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/migrations/executor.py", line 247, in apply_migration
peermetrics-api-1       |     migration_recorded = True
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 110, in __exit__
peermetrics-api-1       |     self.execute(sql)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/schema.py", line 137, in execute
peermetrics-api-1       |     cursor.execute(sql, params)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
peermetrics-api-1       |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
peermetrics-api-1       |     return executor(sql, params, many, context)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
peermetrics-api-1       |     return self.cursor.execute(sql, params)
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 89, in __exit__
peermetrics-api-1       |     raise dj_exc_value.with_traceback(traceback) from exc_value
peermetrics-api-1       |   File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
peermetrics-api-1       |     return self.cursor.execute(sql, params)
peermetrics-api-1       | django.db.utils.ProgrammingError: relation "users" does not exist
peermetrics-api-1       |
peermetrics-api-1 exited with code 1

There might be a simple solution to this but I'm not that familiar with Django and its migration process, and I've not seen any sign that configurations should be modified in order to make it work, so I suppose it's an issue.

Thanks in advance!

**Comment by onel** [comment]
That's a good catch @scarecrow98. Looking into it

**Comment by onel** [comment]
I pushed a fix for this.
The problem was that the API container was running the Django migrations automatically on start which is an issue the first time it is started. Not on subsequent runs.

I've removed that so now, the migrations must be ran manually.
This is also best practice, tbh. It should have been like that.

To get it up and running, follow the steps [here](https://github.com/peermetrics/peermetrics?tab=readme-ov-file#how-to-run-locally):
##### 1.1 Run migrations

Before running the containers for the first time we need to run the Django migrations. This is a one time step.

```sh
docker-compose run api sh
```

And inside the container, run:

```sh
python manage.py makemigrations app
python manage.py migrate
```

LMK if this helps.

Thanks for opening the issue 🙏

**Comment by scarecrow98** [comment]
Dashboard up and running, works like a charm! Thanks for you fix, looking forward to see this thing in action! :)

Closing the issue!
